{% include "_header.jinja" %}
{% if language == "go" %}
FROM [[ lang.buildImage ]] AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/app ./...

FROM [[ lang.runtimeImage ]]
COPY --from=build /out/app /app
ENTRYPOINT ["/app"]
{% elif language == "rust" %}
FROM [[ lang.buildImage ]] AS build
WORKDIR /src
COPY . .
RUN cargo build --release

FROM [[ lang.runtimeImage ]]
COPY --from=build /src/target/release/app /app
ENTRYPOINT ["/app"]
{% endif %}
