[[- if eq .Language "go" -]]
FROM [[ .Lang.BuildImage ]] AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/app ./...

FROM [[ .Lang.RuntimeImage ]]
COPY --from=build /out/app /app
ENTRYPOINT ["/app"]
[[- else if eq .Language "rust" -]]
FROM [[ .Lang.BuildImage ]] AS build
WORKDIR /src
COPY . .
RUN cargo build --release

FROM [[ .Lang.RuntimeImage ]]
COPY --from=build /src/target/release/app /app
ENTRYPOINT ["/app"]
[[- end ]]
